require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LearnsController do

  # This should return the minimal set of attributes required to create a valid
  # Learn. As you add validations to Learn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "what" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LearnsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all learns as @learns" do
      learn = Learn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:learns).should eq([learn])
    end
  end

  describe "GET show" do
    it "assigns the requested learn as @learn" do
      learn = Learn.create! valid_attributes
      get :show, {:id => learn.to_param}, valid_session
      assigns(:learn).should eq(learn)
    end
  end

  describe "GET new" do
    it "assigns a new learn as @learn" do
      get :new, {}, valid_session
      assigns(:learn).should be_a_new(Learn)
    end
  end

  describe "GET edit" do
    it "assigns the requested learn as @learn" do
      learn = Learn.create! valid_attributes
      get :edit, {:id => learn.to_param}, valid_session
      assigns(:learn).should eq(learn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Learn" do
        expect {
          post :create, {:learn => valid_attributes}, valid_session
        }.to change(Learn, :count).by(1)
      end

      it "assigns a newly created learn as @learn" do
        post :create, {:learn => valid_attributes}, valid_session
        assigns(:learn).should be_a(Learn)
        assigns(:learn).should be_persisted
      end

      it "redirects to the created learn" do
        post :create, {:learn => valid_attributes}, valid_session
        response.should redirect_to(Learn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved learn as @learn" do
        # Trigger the behavior that occurs when invalid params are submitted
        Learn.any_instance.stub(:save).and_return(false)
        post :create, {:learn => { "what" => "invalid value" }}, valid_session
        assigns(:learn).should be_a_new(Learn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Learn.any_instance.stub(:save).and_return(false)
        post :create, {:learn => { "what" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested learn" do
        learn = Learn.create! valid_attributes
        # Assuming there are no other learns in the database, this
        # specifies that the Learn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Learn.any_instance.should_receive(:update_attributes).with({ "what" => "MyString" })
        put :update, {:id => learn.to_param, :learn => { "what" => "MyString" }}, valid_session
      end

      it "assigns the requested learn as @learn" do
        learn = Learn.create! valid_attributes
        put :update, {:id => learn.to_param, :learn => valid_attributes}, valid_session
        assigns(:learn).should eq(learn)
      end

      it "redirects to the learn" do
        learn = Learn.create! valid_attributes
        put :update, {:id => learn.to_param, :learn => valid_attributes}, valid_session
        response.should redirect_to(learn)
      end
    end

    describe "with invalid params" do
      it "assigns the learn as @learn" do
        learn = Learn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Learn.any_instance.stub(:save).and_return(false)
        put :update, {:id => learn.to_param, :learn => { "what" => "invalid value" }}, valid_session
        assigns(:learn).should eq(learn)
      end

      it "re-renders the 'edit' template" do
        learn = Learn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Learn.any_instance.stub(:save).and_return(false)
        put :update, {:id => learn.to_param, :learn => { "what" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested learn" do
      learn = Learn.create! valid_attributes
      expect {
        delete :destroy, {:id => learn.to_param}, valid_session
      }.to change(Learn, :count).by(-1)
    end

    it "redirects to the learns list" do
      learn = Learn.create! valid_attributes
      delete :destroy, {:id => learn.to_param}, valid_session
      response.should redirect_to(learns_url)
    end
  end

end
